// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCruv54UJGNWGCzifDk420NMTwwCepVQTQ',
    appId: '1:318109838368:android:fa3c509ec3d20855eb2045',
    messagingSenderId: '318109838368',
    projectId: 'ai-fusion-fyp',
    storageBucket: 'ai-fusion-fyp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6F8UBUUQr7xiiv3ixf-l2ta3NT1BeuFc',
    appId: '1:318109838368:ios:9322f6246bebfac6eb2045',
    messagingSenderId: '318109838368',
    projectId: 'ai-fusion-fyp',
    storageBucket: 'ai-fusion-fyp.firebasestorage.app',
    androidClientId: '318109838368-95r56741au48jhb1vh9gnnqmsbu1lo7q.apps.googleusercontent.com',
    iosClientId: '318109838368-se0vsmt23ffps7b9qmjvoggung7k4fna.apps.googleusercontent.com',
    iosBundleId: 'com.maheen.fyp',
  );
}
